name: flutter_map_marker_popup
description: Marker popups for flutter_map.
version: 8.0.0
homepage: https://github.com/pablodelolmo/flutter_map_marker_popup
topics:
  - flutter-map
  - popups

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  animated_stack_widget: ^0.0.4
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
